# fly.toml app configuration file generated for open-worko-server2 on 2026-06-21T21:48:31Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'open-worko-server2'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[env]
  DB_PATH = '/data/worko.db'
  PORT = '8080'
  PUBLIC_DIR = '/app/dashboard/dist'

[[mounts]]
  source = 'worko_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
